import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Banner from "./components/Banner";
import Nav from "./components/Navigation";
import Footer from "./components/Footer";

export default function Home() {
  return (
    <div className="bg-gray-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="w-full max-w-screen-lg m-auto">
        <main className={styles.main}>
          <Banner image="https://tpc.googlesyndication.com/simgad/13682594288002787745" />
          <div className="flex items-stretch justify-between flex-no-wrap space-x-7 mb-10">
            <div className="w-6/12 flex-column">
              <h2 className="font-bold text-2xl pb-2">Top Story</h2>
              <a
                href="https://www.nhlshop.com/"
                className="bg-white h-full w-full flex flex-wrap flex-column rounded-xl overflow-hidden relative shadow-lg"
              >
                <div className="absolute left-0 top-0 z-1 p-4 w-full">
                  <p className="text-sm text-gray-200">BREAKING STORY</p>
                  <p className="text-xl font-semi-bold text-white">
                    Dustin Brown to retire
                  </p>
                </div>
                <Image
                  src="https://cdn.vox-cdn.com/thumbor/7Dakrrzay6RgNFh1EsH5j370tqY=/0x0:4000x2667/1200x800/filters:focal(1680x1014:2320x1654)/cdn.vox-cdn.com/uploads/chorus_image/image/65483999/1180921065.jpg.0.jpg"
                  height={332}
                  width={498}
                  alt="Top Story"
                />
                <div className="p-5">
                  <h4 className="font-semi-bold text-lg pb-1">
                    Kings to Retire Dustin Brown‘s No. 23 and Unveil Statue
                  </h4>
                  <p className="text-gray-600 text-base">
                    Ceremony to Honor Two-Time Stanley Cup Captain and Franchise
                    Icon Set for Feb. 11 at Crypto.com Arena
                  </p>
                </div>
              </a>
            </div>
            <div className="w-6/12 flex-column rounded-xl">
              <h2 className="font-bold text-2xl pb-2">Feature Product</h2>
              <a
                href="https://www.nhlshop.com/"
                className="bg-white h-full w-full flex rounded-xl overflow-hidden items-center justify-center relative shadow-lg"
              >
                <Image
                  src="https://fanatics.frgimages.com/FFImage/thumb.aspx?i=/productimages/_4464000/ff_4464752-163e2be83c6e9b688e2e_full.jpg"
                  height={400}
                  width={400}
                  alt="Featured Product"
                />
                <div className="bg-white absolute left-0 top-0 z-6 p-4 w-full">
                  <p className="text-sm text-orange-500">NEW</p>
                  <p className="text-xl font-semi-bold">
                    LA Kings &quot;On the Ice&quot; Snapback Cap
                  </p>
                </div>
                <div className="bg-white absolute left-0 bottom-0 z-6 p-4 w-full flex flex-no-wrap items-center justify-between">
                  <div>
                    <p className="text-3xl font-semi-bold text-orange-500 w-full">
                      $29.99
                    </p>
                    <p className="text-base w-full">One size fits all</p>
                  </div>
                  <button className="px-7 py-1 bg-blue-500 rounded-md text-white">
                    Add to Cart
                  </button>
                </div>
              </a>
            </div>
          </div>
          <Banner image="https://tpc.googlesyndication.com/simgad/8572446148985133851" />
          <div className="bg-white flex-column rounded-xl overflow-hidden shadow-lg px-5 py-3">
            <a
              className="flex items-center justify-start py-2"
              href="https://runsignup.com/Race/CA/RedondoBeach/LAKings5KinRedondoBeach"
            >
              <Image
                src="https://cms.nhl.bamgrid.com/images/photos/335101762/1704x960/cut.jpg"
                height={113}
                width={200}
                alt="Top Story"
              />
              <div className="pl-4">
                <h4 className="font-semi-bold text-lg pb-1">
                  Join the LA Kings birthday Club!
                </h4>
                <p className="text-gray-600 text-sm">
                  On your birthday, you&apos;ll receive: Two (2) complimentary
                  tickets*, Up to 25% off additional tickets you purchase, 10%
                  off at TEAM LA online
                </p>
              </div>
            </a>
            <a
              className="flex items-center justify-start py-2"
              href="https://www.nhl.com/kings/fans/birthday"
            >
              <Image
                src="https://cms.nhl.bamgrid.com/images/photos/335101428/1136x640/cut.jpg"
                height={113}
                width={200}
                alt="Top Story"
              />
              <div className="pl-4">
                <h4 className="font-semi-bold text-lg pb-1">
                  LA Kings 5K In Redondo Beach
                </h4>
                <p className="text-gray-600 text-sm">
                  The 5K is set to take place on September 10th at 8:00am and
                  will be held in the beautiful Riviera Village area of South
                  Redondo Beach.
                </p>
              </div>
            </a>
          </div>
        </main>
      </div>
      <Footer />
    </div>
  );
}
